import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="user")
@SessionScoped
public class UserBean{
    public String[] favNumber3;
    public String[] getFavNumber3() {
        return favNumber3;
    }

    public void setFavNumber3(String[] favNumber3) {
        this.favNumber3 = favNumber3;
    }

    //Generated by Map
    private static Map<String,String> number3Value;
    static{
        number3Value = new LinkedHashMap<String,String>();
        number3Value.put("Number3 - 1", "1");
        number3Value.put("Number3 - 2", "2");
        number3Value.put("Number3 - 3", "3");
        number3Value.put("Number3 - 4", "4");
        number3Value.put("Number3 - 5", "5");
    }

    public Map<String,String> getFavNumber3Value() {
        return number3Value;
    }

    public String getfavNumber3InString() {
        return Arrays.toString(favNumber3);
    }
}
